package com.my.mybatistest.vo;

public class UserBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAge
     *
     * @mbg.generated
     */
    private Integer userage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAddress
     *
     * @mbg.generated
     */
    private String useraddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param username the value for user.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAge
     *
     * @return the value of user.userAge
     *
     * @mbg.generated
     */
    public Integer getUserage() {
        return userage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAge
     *
     * @param userage the value for user.userAge
     *
     * @mbg.generated
     */
    public void setUserage(Integer userage) {
        this.userage = userage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAddress
     *
     * @return the value of user.userAddress
     *
     * @mbg.generated
     */
    public String getUseraddress() {
        return useraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAddress
     *
     * @param useraddress the value for user.userAddress
     *
     * @mbg.generated
     */
    public void setUseraddress(String useraddress) {
        this.useraddress = useraddress;
    }
}